### ISSUE TITLE
Missing Functions: ANCHORARRAY, LET, FILTER, XMATCH, SORT

### ISSUE THREAD

**Issue by Kyle1297** [formulajs/formulajs#117] opened 2022-10-26 22:24 UTC
Hey there,

I'm using `XLSX_CALC` to recalculate an excel file and I am getting errors that the following functions are not found:
- ANCHORARRAY
- LET
- _xlws.FILTER
- XMATCH
- _xlws.SORT

Example error: `Error: "Sheet - Hidden"!D83: Function _xlws.FILTER not found`

Happy to assist with adding the above functions. Have no idea how to start though, including where we even find equivalent excel logic for these functions.

Need this for a work project, so it is rather urgent. Ready to help ASAP

**Comment by nicolashefti** [comment] 2022-10-27 15:04
Hi @Kyle1297 

1) To add a new function, you can start from the Excel definition (exemple for [SORT](https://support.microsoft.com/en-us/office/sort-function-22f63bd0-ccc8-492f-953d-c20e8e44b86c)). There is no code you can copy-paste.

You could also check if it is implemented in Hyperformula.

Formulajs is writting in a TDD way. So if you implement correctly your tests cases, you should be able to write the code to make things work.

2) You can also simplify your original XLSX file to remove missing functions (LET is a shortcut for efficiency, XMATCH is a better MATCH).

I would start with 2) if this is urgent.

**Comment by Kyle1297** [comment] 2022-11-01 23:50
Thanks, @nicolashefti. Created the first PR of a few to come. Started with the XMATCH function, let me know how it fares.

We would like to just do option 2 but the excel spreadsheet gets updated periodically by an external provider so we want to make sure we don't have to re-adjust the formulas every time. So, gotta try adding all the functions. Thanks for the suggestion though!

**Comment by Kyle1297** [comment] 2022-11-01 23:52
@nicolashefti I can't find any info on the ANCHORARRAY function. Do you have any idea what it is? I can't locate it in our excel spreadsheet either

**Comment by Kyle1297** [comment] 2022-12-08 04:27
Some other missing formulas:
- GETPIVOTDATA
- SINGLE
- TEXT
- CELL

**Comment by nicolashefti** [comment] 2022-12-09 09:16
Hi @Kyle1297 

Using these pages : 
- https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188
- https://support.microsoft.com/en-us/office/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb

I would say:

**SINGLE**: is not listed in the available functions?

**GETPIVOTDATA**: Formulajs doesn't know about PivotTable. I don't see how this could be implemented.

**TEXT**: thanks for the PR, I'll check it.

**CELL**: is an "information function" (like ISFORMULA). It's difficult to reproduce because Formulajs does not use a Cell but only values: number, string, ...

Maybe a discussion to start: define a standard Cell Object? But that would mean a lot of refactoring of existing functions to handle this new standard object. @bornova any thoughts on this?

On the other hand, most functions use our utility helper to parse arguments. The Cell object could be handled there.

To me, a pre-requisite to all this would be to move to TS to add strong typing...

**Comment by nicolashefti** [comment] 2022-12-13 16:01
@Kyle1297 thanks for all the new functions you are proposing. I'll focus 2 PR at the time if you don't mind  (_Stop doing, start finishing_). I started with SORT and TEXT. Let me know if you prefer another order.

**Comment by Kyle1297** [comment] 2022-12-13 23:29
> GETPIVOTDATA: Formulajs doesn't know about PivotTable. I don't see how this could be implemented.

I am not too sure either. I might see if it is possible using the [xlsx-calc](https://github.com/fabiooshiro/xlsx-calc) library directly

**Comment by Kyle1297** [comment] 2022-12-13 23:30
> To me, a pre-requisite to all this would be to move to TS to add strong typing...

Very much for TS. I think it just provides peace of mind, in general

**Comment by Kyle1297** [comment] 2022-12-13 23:31
> @Kyle1297 thanks for all the new functions you are proposing. I'll focus 2 PR at the time if you don't mind (Stop starting, start finishing). I started with SORT and TEXT. Let me know if you prefer another order.

Hahaa, thanks @nicolashefti. All are important, so any order works

**Comment by Kyle1297** [comment] 2022-12-13 23:33
> SINGLE: is not listed in the available functions?

See https://github.com/formulajs/formulajs/pull/125 regarding this.

**Comment by Kyle1297** [comment] 2022-12-17 15:17
Another missing function: XLOOKUP

https://support.microsoft.com/en-us/office/xlookup-function-b7fd680e-6d10-43e6-84f9-88eae8bf5929

**Comment by nicolashefti** [comment] 2023-05-31 10:29
Related PR closed by @Kyle1297

**Closed by nicolashefti** 2023-05-31 10:29 UTC
Labels: enhancement
